"""add_work_experience_education_certification_and_profile_fields

Revision ID: 0850b6176e71
Revises: 797b677a8e6a
Create Date: 2026-06-03 06:41:26.422469

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0850b6176e71"
down_revision: Union[str, None] = "797b677a8e6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_certification",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuing_organization", sa.String(length=255), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("credential_id", sa.String(length=255), nullable=True),
        sa.Column("credential_url", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidate_education",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column("degree", sa.String(length=255), nullable=False),
        sa.Column("field_of_study", sa.String(length=255), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidate_work_experience",
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidate_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "candidate_profile",
        sa.Column("github_url", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "candidate_profile",
        sa.Column("portfolio_url", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "candidate_profile",
        sa.Column("preferred_work_models", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "candidate_profile",
        sa.Column("preferred_locations", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "candidate_profile",
        sa.Column(
            "open_to_relocation",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "jobs", sa.Column("required_skills", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("seniority_level", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column("openings_count", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "jobs", sa.Column("required_years_experience", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "jobs",
        "title",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "title",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("jobs", "required_years_experience")
    op.drop_column("jobs", "openings_count")
    op.drop_column("jobs", "seniority_level")
    op.drop_column("jobs", "required_skills")
    op.drop_column("candidate_profile", "open_to_relocation")
    op.drop_column("candidate_profile", "preferred_locations")
    op.drop_column("candidate_profile", "preferred_work_models")
    op.drop_column("candidate_profile", "portfolio_url")
    op.drop_column("candidate_profile", "github_url")
    op.drop_table("candidate_work_experience")
    op.drop_table("candidate_education")
    op.drop_table("candidate_certification")
    # ### end Alembic commands ###
