"""add_cv_parsing_costs

Revision ID: 1022ea7b7a88
Revises: ea15b920ec8d
Create Date: 2026-06-14 19:09:43.783343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1022ea7b7a88'
down_revision: Union[str, None] = 'ea15b920ec8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_parsing_costs',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['parsed_cv_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cv_parsing_costs_created_at', 'cv_parsing_costs', ['created_at'], unique=False)
    op.create_index('ix_cv_parsing_costs_submission_id', 'cv_parsing_costs', ['submission_id'], unique=False)
    op.alter_column('candidate_profile', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_profile', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_cv_parsing_costs_submission_id', table_name='cv_parsing_costs')
    op.drop_index('ix_cv_parsing_costs_created_at', table_name='cv_parsing_costs')
    op.drop_table('cv_parsing_costs')
    # ### end Alembic commands ###
