"""added match_score and score_computed_at to application table

Revision ID: 1cd84b3a7473
Revises: ffcf82b6586a
Create Date: 2026-06-05 10:09:52.958015

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cd84b3a7473"
down_revision: Union[str, None] = "ffcf82b6586a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("applications", sa.Column("match_score", sa.Integer(), nullable=True))
    op.add_column(
        "applications",
        sa.Column("score_computed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "score_computed_at")
    op.drop_column("applications", "match_score")
    # ### end Alembic commands ###
