"""add moderation_status to jobs

Revision ID: 33142ad61fa0
Revises: b712500afb5c
Create Date: 2026-06-04 10:31:35.233392

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33142ad61fa0'
down_revision: Union[str, None] = 'b712500afb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('moderation_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.execute("UPDATE jobs SET moderation_status = 'APPROVED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'moderation_status')
    # ### end Alembic commands ###
