"""added_cv_sharing_consent_to_candidates_profile

Revision ID: 4ee45042089b
Revises: 78ab2e6563f1
Create Date: 2026-06-23 17:12:13.145992

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ee45042089b"
down_revision: Union[str, None] = "78ab2e6563f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_profile",
        sa.Column(
            "cv_sharing_consent",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate_profile", "cv_sharing_consent")
    # ### end Alembic commands ###
