"""add_contact_submissions_table

Revision ID: 5b1ee5fdfe81
Revises: 1cd84b3a7473
Create Date: 2026-06-09 10:45:51.609315

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b1ee5fdfe81'
down_revision: Union[str, None] = '1cd84b3a7473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('inquiry_type', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidate_profile', sa.Column('expect3ed_currency', sa.String(length=3), nullable=True))
    op.drop_column('candidate_profile', 'expected_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profile', sa.Column('expected_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_column('candidate_profile', 'expect3ed_currency')
    op.drop_table('contact_submissions')
    # ### end Alembic commands ###
