"""add linkedin_url to candidate_profile

Revision ID: 67aecdac4d27
Revises: 2a4fe6012739
Create Date: 2026-05-23 03:16:10.754716

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67aecdac4d27"
down_revision: Union[str, None] = "2a4fe6012739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_profile",
        sa.Column("linkedin_url", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate_profile", "linkedin_url")
    # ### end Alembic commands ###
