"""add work location to Job model

Revision ID: 727c9e286762
Revises: f72a472e26ab
Create Date: 2026-05-15 12:54:48.330245

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "727c9e286762"
down_revision: str | None = "f72a472e26ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("work_location", sa.String(length=20), server_default="LOCAL", nullable=False))
    op.create_index(op.f("ix_jobs_work_location"), "jobs", ["work_location"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_work_location"), table_name="jobs")
    op.drop_column("jobs", "work_location")
    # ### end Alembic commands ###
