"""added_job_access_tokens_and_talent_pool_profiles

Revision ID: 78ab2e6563f1
Revises: df93748028c5
Create Date: 2026-06-23 17:03:21.719894

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78ab2e6563f1'
down_revision: Union[str, None] = 'df93748028c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_access_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('disclose_names', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_access_tokens_expires_at'), 'job_access_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_job_access_tokens_revoked_at'), 'job_access_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_job_access_tokens_token'), 'job_access_tokens', ['token'], unique=True)
    op.create_table('talent_pool_profiles',
    sa.Column('parsed_submission_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('sourced_for_job_id', sa.UUID(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('promoted_application_id', sa.UUID(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_invite_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parsed_submission_id'], ['parsed_cv_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sourced_for_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promoted_application_id')
    )
    op.create_index(op.f('ix_talent_pool_profiles_source'), 'talent_pool_profiles', ['source'], unique=False)
    op.create_index(op.f('ix_talent_pool_profiles_status'), 'talent_pool_profiles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_talent_pool_profiles_status'), table_name='talent_pool_profiles')
    op.drop_index(op.f('ix_talent_pool_profiles_source'), table_name='talent_pool_profiles')
    op.drop_table('talent_pool_profiles')
    op.drop_index(op.f('ix_job_access_tokens_token'), table_name='job_access_tokens')
    op.drop_index(op.f('ix_job_access_tokens_revoked_at'), table_name='job_access_tokens')
    op.drop_index(op.f('ix_job_access_tokens_expires_at'), table_name='job_access_tokens')
    op.drop_table('job_access_tokens')
    # ### end Alembic commands ###
