"""add_application_deadline_to_jobs

Revision ID: 797b677a8e6a
Revises: 8494d59c61f2
Create Date: 2026-05-29 11:43:32.771770

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "797b677a8e6a"
down_revision: Union[str, None] = "8494d59c61f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("application_deadline", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_jobs_application_deadline"),
        "jobs",
        ["application_deadline"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_application_deadline"), table_name="jobs")
    op.drop_column("jobs", "application_deadline")
    # ### end Alembic commands ###
