"""add_embedding_columns_to_candidate_profile_and_jobs

Revision ID: 7af353621b03
Revises: p12_0001
Create Date: 2026-07-01 07:29:16.464836

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7af353621b03"
down_revision: Union[str, None] = "p12_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_profile",
        sa.Column(
            "profile_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
    )
    op.add_column(
        "candidate_profile",
        sa.Column("embedding_source_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "candidate_profile",
        sa.Column("embedding_generated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "job_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
    )
    op.add_column(
        "jobs", sa.Column("embedding_source_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column("embedding_generated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "embedding_generated_at")
    op.drop_column("jobs", "embedding_source_hash")
    op.drop_column("jobs", "job_embedding")
    op.drop_column("candidate_profile", "embedding_generated_at")
    op.drop_column("candidate_profile", "embedding_source_hash")
    op.drop_column("candidate_profile", "profile_embedding")
    # ### end Alembic commands ###
