"""add_cv_parse_status_and_submission_id_to_candidate_cvs

Revision ID: 94cb6946e696
Revises: 1022ea7b7a88
Create Date: 2026-06-15 20:02:55.531991

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94cb6946e696'
down_revision: Union[str, None] = '1022ea7b7a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_cv', sa.Column('cv_parse_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('candidate_cv', sa.Column('submission_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_cv', 'parsed_cv_submissions', ['submission_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_constraint(None, 'candidate_cv', type_='foreignkey')
    op.drop_column('candidate_cv', 'submission_id')
    op.drop_column('candidate_cv', 'cv_parse_status')
    # ### end Alembic commands ###
