"""created_profile_views_added visibility status

Revision ID: 9a0786909cc7
Revises: 0850b6176e71
Create Date: 2026-06-03 14:42:12.138119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0786909cc7'
down_revision: Union[str, None] = '0850b6176e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_views',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidate_profile', sa.Column('visibility', sa.String(length=15), server_default='APPLIED_ONLY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profile', 'visibility')
    op.drop_table('profile_views')
    # ### end Alembic commands ###
