"""added company_description to EmployerProfile table

Revision ID: 9c78739fc069
Revises: 727c9e286762
Create Date: 2026-05-16 11:49:12.655049

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c78739fc069"
down_revision: str | None = "727c9e286762"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employer_profiles", sa.Column("company_description", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employer_profiles", "company_description")
    # ### end Alembic commands ###
