"""add_credits_and_introduction_requests

Revision ID: a90a457e7f79
Revises: a1b2c3d4e5f6
Create Date: 2026-07-16 12:28:11.375054

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a90a457e7f79"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_transactions",
        sa.Column("employer_id", sa.UUID(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_transactions_employer_id"),
        "credit_transactions",
        ["employer_id"],
        unique=False,
    )
    op.create_table(
        "employer_credits",
        sa.Column("employer_id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance >= 0", name="ck_employer_credits_balance_non_negative"
        ),
        sa.ForeignKeyConstraint(["employer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employer_id"),
    )
    op.create_table(
        "introduction_requests",
        sa.Column("employer_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("talent_pool_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["talent_pool_profile_id"], ["talent_pool_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_introduction_requests_employer_id"),
        "introduction_requests",
        ["employer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_introduction_requests_job_id"),
        "introduction_requests",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_introduction_requests_status"),
        "introduction_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_introduction_requests_talent_pool_profile_id"),
        "introduction_requests",
        ["talent_pool_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_introduction_requests_token"),
        "introduction_requests",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_introduction_requests_token"), table_name="introduction_requests"
    )
    op.drop_index(
        op.f("ix_introduction_requests_talent_pool_profile_id"),
        table_name="introduction_requests",
    )
    op.drop_index(
        op.f("ix_introduction_requests_status"), table_name="introduction_requests"
    )
    op.drop_index(
        op.f("ix_introduction_requests_job_id"), table_name="introduction_requests"
    )
    op.drop_index(
        op.f("ix_introduction_requests_employer_id"), table_name="introduction_requests"
    )
    op.drop_table("introduction_requests")
    op.drop_table("employer_credits")
    op.drop_index(
        op.f("ix_credit_transactions_employer_id"), table_name="credit_transactions"
    )
    op.drop_table("credit_transactions")
    # ### end Alembic commands ###
