"""add email_verified and update account status values

Revision ID: b83276b19f01
Revises: 69c46e0f2544
Create Date: 2026-05-14 05:40:41.064780

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b83276b19f01"
down_revision: str | None = "69c46e0f2544"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )

    # Migrate existing data after creating the column
    op.execute(
        "UPDATE users SET account_status = 'DEACTIVATED' WHERE account_status = 'INACTIVE'"
    )
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
