"""added_ai_data_to_applications

Revision ID: df93748028c5
Revises: aaa001
Create Date: 2026-06-23 15:38:22.034186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df93748028c5'
down_revision: Union[str, None] = 'aaa001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('ai_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('ai_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('ai_fit_summary', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('ai_score_job_hash', sa.String(length=64), nullable=True))
    op.add_column('applications', sa.Column('ai_score_cv_hash', sa.String(length=64), nullable=True))
    op.add_column('applications', sa.Column('ai_score_computed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'ai_score_computed_at')
    op.drop_column('applications', 'ai_score_cv_hash')
    op.drop_column('applications', 'ai_score_job_hash')
    op.drop_column('applications', 'ai_fit_summary')
    op.drop_column('applications', 'ai_weaknesses')
    op.drop_column('applications', 'ai_strengths')
    op.drop_column('applications', 'ai_score')
    # ### end Alembic commands ###
