"""add_candidate_profile_id_to_talent_pool_make_submission_nullable

Revision ID: e046b6082572
Revises: 4ee45042089b
Create Date: 2026-06-29 16:53:18.324504

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e046b6082572'
down_revision: Union[str, None] = '4ee45042089b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent_pool_profiles', sa.Column('candidate_profile_id', sa.UUID(), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_fit_summary', sa.Text(), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_score_job_hash', sa.String(length=64), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_score_cv_hash', sa.String(length=64), nullable=True))
    op.add_column('talent_pool_profiles', sa.Column('ai_score_computed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('talent_pool_profiles', 'parsed_submission_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'talent_pool_profiles', ['candidate_profile_id'])
    op.create_foreign_key(None, 'talent_pool_profiles', 'candidate_profile', ['candidate_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'talent_pool_profiles', type_='foreignkey')
    op.drop_constraint(None, 'talent_pool_profiles', type_='unique')
    op.alter_column('talent_pool_profiles', 'parsed_submission_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('talent_pool_profiles', 'ai_score_computed_at')
    op.drop_column('talent_pool_profiles', 'ai_score_cv_hash')
    op.drop_column('talent_pool_profiles', 'ai_score_job_hash')
    op.drop_column('talent_pool_profiles', 'ai_fit_summary')
    op.drop_column('talent_pool_profiles', 'ai_weaknesses')
    op.drop_column('talent_pool_profiles', 'ai_strengths')
    op.drop_column('talent_pool_profiles', 'ai_score')
    op.drop_column('talent_pool_profiles', 'candidate_profile_id')
    # ### end Alembic commands ###
