"""add partial unique index one default cv per candidate

Revision ID: e8b06ec62bcf
Revises: 67aecdac4d27
Create Date: 2026-05-23 16:38:06.336070

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8b06ec62bcf'
down_revision: Union[str, None] = '67aecdac4d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE UNIQUE INDEX one_default_cv_per_candidate
        ON candidate_cv (candidate_id)
        WHERE is_default = TRUE
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("one_default_cv_per_candidate", table_name="candidate_cv")
    # ### end Alembic commands ###
