"""add_parsed_cv_submissions_table

Revision ID: ea15b920ec8d
Revises: b20dc6ad05aa
Create Date: 2026-06-14 18:47:57.183959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea15b920ec8d"
down_revision: Union[str, None] = "b20dc6ad05aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsed_cv_submissions",
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("r2_key", sa.Text(), nullable=True),
        sa.Column("cv_text_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "parse_status",
            sa.String(length=20),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "parsed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "deterministic_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("llm_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flag_reasons", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_parsed_cv_submissions_cv_text_hash",
        "parsed_cv_submissions",
        ["cv_text_hash"],
        unique=False,
    )
    op.create_index(
        "ix_parsed_cv_submissions_parse_status",
        "parsed_cv_submissions",
        ["parse_status"],
        unique=False,
    )
    op.create_index(
        "ix_parsed_cv_submissions_uploaded_by",
        "parsed_cv_submissions",
        ["uploaded_by"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_parsed_cv_submissions_uploaded_by", table_name="parsed_cv_submissions"
    )
    op.drop_index(
        "ix_parsed_cv_submissions_parse_status", table_name="parsed_cv_submissions"
    )
    op.drop_index(
        "ix_parsed_cv_submissions_cv_text_hash", table_name="parsed_cv_submissions"
    )
    op.drop_table("parsed_cv_submissions")
    # ### end Alembic commands ###
