"""added_show_cv_field_to_tale

Revision ID: f1ca5d013180
Revises: b6f2d9a4e8c1
Create Date: 2026-07-29 15:42:51.505030

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1ca5d013180"
down_revision: Union[str, None] = "b6f2d9a4e8c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column(
        "job_access_tokens",
        sa.Column(
            "show_cv", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_access_tokens", "show_cv")
    # ### end Alembic commands ###
