"""added new email_verified_at to the User model and used_at to the InviteToken Table

Revision ID: f72a472e26ab
Revises: 4a01460264af
Create Date: 2026-05-15 11:44:41.275994

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f72a472e26ab"
down_revision: str | None = "4a01460264af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invite_tokens", sa.Column("used_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invite_tokens", "used_at")
    # ### end Alembic commands ###
