"""add reason field to Audit log

Revision ID: ffcf82b6586a
Revises: 33142ad61fa0
Create Date: 2026-06-05 01:58:06.381655

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ffcf82b6586a'
down_revision: Union[str, None] = '33142ad61fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit_log', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_audit_log', 'reason')
    # ### end Alembic commands ###
