"""add interviews table and job interview_brief

Revision ID: p22_0007
Revises: p22_0006
Create Date: 2026-08-18 08:16:20.619266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'p22_0007'
down_revision: Union[str, None] = 'p22_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('r2_key', sa.String(length=512), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('video_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_application_id', 'interviews', ['application_id'], unique=True)
    op.create_index('ix_interviews_status', 'interviews', ['status'], unique=False)
    op.add_column('jobs', sa.Column('interview_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'interview_brief')
    op.drop_index('ix_interviews_status', table_name='interviews')
    op.drop_index('ix_interviews_application_id', table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
